version: '3.8'

services:
  postgres:
    image: kartoza/postgis:17-3.5
    container_name: vibeman-postgres
    environment:
      POSTGRES_DB: vibeman
      POSTGRES_USER: vibeman
      POSTGRES_PASSWORD: vibeman_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibeman -d vibeman"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: vibeman-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: